server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/admin_db?createDatabaseIfNotExist=true
    username: root
    password: Ritika@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, circuitbreakers
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  # Zipkin
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

# Resilience4j
resilience4j:
  circuitbreaker:
    instances:
      deliveryService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
      trackingService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
  timelimiter:
    instances:
      deliveryService:
        timeoutDuration: 3s
      trackingService:
        timeoutDuration: 3s
  retry:
    instances:
      deliveryService:
        maxAttempts: 3
        waitDuration: 2s
      trackingService:
        maxAttempts: 3
        waitDuration: 2s
