server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/gateway/auth/**
          filters:
            - RewritePath=/gateway/auth(?<segment>/?.*), /auth${segment}

        - id: delivery-service
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/gateway/deliveries/**
          filters:
            - RewritePath=/gateway/deliveries(?<segment>/?.*), /deliveries${segment}

        - id: tracking-service
          uri: lb://TRACKING-SERVICE
          predicates:
            - Path=/gateway/tracking/**
          filters:
            - RewritePath=/gateway/tracking(?<segment>/?.*), /tracking${segment}

        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/gateway/admin/**
          filters:
            - RewritePath=/gateway/admin(?<segment>/?.*), /admin${segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"

  tracing:
    sampling:
      probability: 1.0

# ZIPKIN
spring.zipkin.base-url: http://localhost:9411
spring.sleuth.enabled: true
