server:
  port: 8082

spring:
  application:
    name: DELIVERY-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/delivery_db
    username: root
    password: Ritika@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  zipkin:
    base-url: http://localhost:9411

# ✅ EUREKA
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

# ✅ ACTUATOR
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  tracing:
    sampling:
      probability: 1.0

# ✅ 🔥 MOST IMPORTANT (Feign + Circuit Breaker CONNECT)
feign:
  circuitbreaker:
    enabled: true

# ✅ CIRCUIT BREAKER CONFIG (NAME MUST MATCH)
resilience4j:
  circuitbreaker:
    instances:
      TRACKING-SERVICE:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
